version: '3.8'
services:
  jekyll:
    image: jekyll:1.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jekyll.rule=Host(`docs.local.kyoodude.site`)"
      - "traefik.http.routers.jekyll.entrypoints=https"
      - "traefik.http.routers.jekyll.tls=true"
      - "traefik.http.services.jekyll.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true